### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ioankont** [hsientzucheng/CP-360-Weakly-Supervised-Saliency#3]
Hello and thank you for your great job. I am an assistant researcher from C.E.R.T.H (Greece). I would like to have access to the whole dataset. From your project's website, i got into your Google Drive Wild 360 dataset, but you uploaded only the 29 GroundTruths. The other 56 are missing. I would like to have access to the whole Dataset and GT. 

Thank you ( email: ioankont@iti.gr or ioankont97@gmail.com)

**Comment by nhavanntd31** [comment]
Hello, since the agreement form has been closed, could you please grant me access to the dataset you have downloaded? I have also sent an email from datnthet16i@gmail.com to you. Please check for my full request email.
